apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-nginx
spec:
  rules:
  - host: sbccc.asia.pwcinternal.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-nginx
            port:
              number: 80